name: Clean rooms

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Setup npmrc
        run: |
          echo "@geoguess:registry=https://npm.pkg.github.com" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{secrets.GITHUB_TOKEN }}" >> .npmrc
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          registry-url: https://registry.npmjs.org/
      - run: npm install -g @geoguess/geoguess-scripts
      - run: 'echo "$KEYS" > keys.json'
        name: Generate keys.json
        shell: bash
        env:
          KEYS: ${{secrets.SERVICE_ACCOUNT}}
      - run: clean-rooms -f keys.json -c ${{secrets.DATABASE_URL }}
