name: Clean rooms

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          registry-url: https://npm.pkg.github.com
      - run: npm install -g @geoguess/geoguess-scripts
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - run: 'echo "$KEYS" > keys.json'
        name: Generate keys.json
        shell: bash
        env:
          KEYS: ${{secrets.SERVICE_ACCOUNT}}
      - run: clean-rooms -f "$(pwd)/keys.json" -d ${{secrets.DATABASE_URL }}
